/* ============================================================
   Love — the daily note for Kenzie.

   Carried over from the wall exactly as it behaved there: once a day,
   inside a morning window starting at LOVE.hour, one of Chad's messages
   fills the screen; tap anywhere to close. "Already shown today" is kept
   per device on purpose — it should greet her on her phone and on the
   wall independently, not once for the whole family.

   The words themselves live in data/love.js, generated byte-for-byte
   from public/config.js. Nothing here edits them.
   ============================================================ */

const Love = (function () {
  const SHOWN_KEY = "house-love-shown";
  const NOW_KEY = "house-love-now-seen";
  const GLYPHS = ["\u{1F49A}", "\u{1F5A4}", "\u{1F495}", "\u{1F334}", "\u{2728}", "\u{1F497}"];

  function conf() {
    return typeof LOVE !== "undefined" && LOVE ? LOVE : null;
  }

  function lsGet(k) {
    try {
      return localStorage.getItem(k);
    } catch (e) {
      return null;
    }
  }
  function lsSet(k, v) {
    try {
      localStorage.setItem(k, v);
    } catch (e) {
      /* private window: she just sees it again next time, no harm */
    }
  }

  /* Same message for the whole day, a different one tomorrow, and — because
     it is the same arithmetic the wall uses — the same one on the wall and
     on her phone. */
  function messageFor(date) {
    const c = conf();
    if (!c || !c.messages || !c.messages.length) return null;
    const d = date || new Date();
    const day = Math.floor(d.getTime() / 86400000);
    return c.messages[((day % c.messages.length) + c.messages.length) % c.messages.length];
  }

  function due(date) {
    const c = conf();
    if (!c || !c.to || !c.messages || !c.messages.length) return false;
    const d = date || new Date();
    const hour = typeof c.hour === "number" ? c.hour : 7;
    const h = d.getHours();
    if (h < hour || h >= hour + 6) return false;
    return lsGet(SHOWN_KEY) !== Fmt.dayKey(d);
  }

  /* The one-time surprise note (LOVE.now), shown once per distinct text —
     the wall's showLoveNow behaviour. */
  function surpriseDue() {
    const c = conf();
    if (!c || !c.now) return false;
    return lsGet(NOW_KEY) !== c.now;
  }

  let open = null;

  function drift(host) {
    const reduce = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduce) return;
    for (let i = 0; i < 14; i++) {
      const g = UI.h("span", {
        class: "love-glyph",
        text: GLYPHS[Math.floor(Math.random() * GLYPHS.length)],
        style: {
          left: Math.random() * 100 + "%",
          fontSize: 18 + Math.random() * 26 + "px",
          animationDelay: Math.random() * 2.2 + "s",
          animationDuration: 3.4 + Math.random() * 2.6 + "s",
        },
      });
      host.appendChild(g);
    }
  }

  function present(eyebrow, message, onClose) {
    if (open) open();
    const glyphs = UI.h("div", { class: "love-glyphs", "aria-hidden": "true" });
    drift(glyphs);

    const closeBtn = UI.h(
      "button",
      { class: "love-close", type: "button" },
      "xoxo  \u{1F48B}"
    );

    const card = UI.h(
      "div",
      { class: "love-card", role: "dialog", "aria-modal": "true", "aria-label": eyebrow },
      UI.h("div", { class: "love-eyebrow", text: eyebrow }),
      UI.h("p", { class: "love-msg", text: message }),
      closeBtn
    );

    const scrim = UI.h("div", { class: "love-scrim" }, glyphs, card);

    function close() {
      if (!open) return;
      open = null;
      scrim.classList.add("love-out");
      document.removeEventListener("keydown", onKey);
      setTimeout(function () {
        scrim.remove();
      }, 260);
      if (onClose) onClose();
    }
    function onKey(e) {
      if (e.key === "Escape") close();
    }

    scrim.addEventListener("click", close);
    closeBtn.addEventListener("click", function (e) {
      e.stopPropagation();
      close();
    });
    document.addEventListener("keydown", onKey);

    open = close;
    document.body.appendChild(scrim);
    closeBtn.focus({ preventScroll: true });
  }

  function show(date) {
    const c = conf();
    const msg = messageFor(date);
    if (!c || !msg) return false;
    const d = date || new Date();
    lsSet(SHOWN_KEY, Fmt.dayKey(d));
    present("Good morning, " + c.to + " \u{1F49A}", msg);
    return true;
  }

  function showSurprise() {
    const c = conf();
    if (!c || !c.now) return false;
    lsSet(NOW_KEY, c.now);
    present("\u{1F48C} A surprise note for " + c.to, c.now);
    return true;
  }

  /* Boot calls this once; it checks every minute so the note lands at the
     hour, exactly as the wall does. */
  let ticking = false;
  function watch() {
    if (ticking) return;
    ticking = true;
    function tick() {
      try {
        if (surpriseDue()) showSurprise();
        else if (due()) show();
      } catch (e) {
        /* the love note must never take the app down */
      }
    }
    tick();
    setInterval(tick, 60 * 1000);
  }

  return {
    messageFor: messageFor,
    due: due,
    show: show,
    showSurprise: showSurprise,
    watch: watch,
  };
})();
